apiVersion: v1
kind: Service
metadata:
  name: test-service
  namespace: test
  labels:
    istio.io/rev: asm-1-17
spec:
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: test-vs
  namespace: test
spec:
  hosts:
  - test-service.test.svc.cluster.local