name: deployment-churn

{{$churn := DefaultParam .CL2_REPEATS 5}}  # How many times to repeat the churn phase
{{$totalPods := DefaultParam .CL2_TOTAL_PODS 5000}}
{{$serviceSize := DefaultParam .CL2_SERVICE_SIZE 1000}}
{{$namespaces := 1}}
{{$deploymentSize := DefaultParam .CL2_DEPLOYMENT_SIZE 1}}
{{$loadTestThroughput := DefaultParam .CL2_LOAD_TEST_THROUGHPUT 1000}}

{{$latencyPodImage := DefaultParam .CL2_LATENCY_POD_IMAGE "mcr.microsoft.com/oss/kubernetes/pause:3.6"}}
{{$latencyPodCpu := DefaultParam .CL2_LATENCY_POD_CPU 10}} #mCPU
{{$latencyPodMemory := DefaultParam .CL2_LATENCY_POD_MEMORY 50}} #MB

{{$podStartupLatencyThreshold := DefaultParam .CL2_POD_STARTUP_LATENCY_THRESHOLD "60s"}}
{{$podsPerNamespace := DivideInt $totalPods $namespaces}}
{{$deploymentsPerNamespace := DivideInt $podsPerNamespace $deploymentSize}}

{{$deploymentQPS := DivideFloat $loadTestThroughput $deploymentSize}}
{{$defaultQps := DefaultParam .CL2_DEFAULT_QPS 1000}}

namespace:
  number: {{$namespaces}} # testing everything in one namespace
  deleteStaleNamespaces: true
  deleteAutomanagedNamespaces: true
  enableExistingNamespaces: false

tuningSets:
  - name: Sequence
    parallelismLimitedLoad:
      parallelismLimit: 1
  # TODO(https://github.com/kubernetes/perf-tests/issues/1024): This TuningSet is used only for pod-startup-latency, get rid of it
  # Uniform5qps: for each running phase, use 5 qps.
  - name: Uniform5qps
    qpsLoad:
      qps: 5
  # default is a tuningset that is meant to be used when we don't have any specific requirements on pace of operations.
  - name: default
    globalQPSLoad:
      qps: {{$defaultQps}}
      burst: 1
  - name: DeploymentCreateQps
    qpsLoad:
      qps: {{$deploymentQPS}}
  - name: DeploymentDeleteQps
    qpsLoad:
      qps: {{$deploymentQPS}}

steps:
  - name: Log - nodes={{.Nodes}}, namespaces={{$namespaces}}, totalPods={{$totalPods}},deploymentQPS={{$deploymentQPS}}, churn={{$churn}}, serviceSize={{$serviceSize}}
    measurements:
    - Identifier: Dummy
      Method: Sleep
      Params:
        action: start
        duration: 1ms

  - name: start measurements
    measurements:
      - Identifier: PodStartupLatency
        Method: PodStartupLatency
        Params:
          action: start
          labelSelector: group = deployment-churn
          threshold: {{$podStartupLatencyThreshold}}
      - Identifier: WaitForRunningLatencyDeployments
        Method: WaitForControlledPodsRunning
        Params:
          action: start
          checkIfPodsAreUpdated: true
          apiVersion: apps/v1
          kind: Deployment
          labelSelector: group = deployment-churn
          operationTimeout: 15m
      - Identifier: SchedulingThroughput
        Method: SchedulingThroughput
        Params:
          action: start
      - Identifier: APIResponsivenessPrometheusSimple
        Method: APIResponsivenessPrometheus
        Params:
          action: start
  
  - module:
      path: large-config-service.yaml
      params:
        actionName: "Creating"
        namespaces: {{$namespaces}}
        replicasPerNamespace: {{$serviceSize}}

  {{range $i := Loop $churn}}
  - name: Sleep for  30s before start creating deployments - iteration {{$i}}
    measurements:
    - Identifier: sleep
      Method: Sleep
      Params:
        duration: 30s
  - name: Creating Deployments
    phases:
      - namespaceRange:
          min: 1
          max: {{$namespaces}}
        replicasPerNamespace: {{$deploymentsPerNamespace}}
        tuningSet: DeploymentCreateQps
        objectBundle:
          - basename: deployment-churn
            objectTemplatePath: simple-deployment.yaml
            templateFillMap:
              Replicas: {{$deploymentSize}}
              Group: deployment-churn
              CpuRequest: {{$latencyPodCpu}}m
              MemoryRequest: {{$latencyPodMemory}}M
              Image: {{$latencyPodImage}}
              SvcName: large-service
              serviceSize: {{$serviceSize}}

  - name: Waiting for latency pods to be running
    measurements:
      - Identifier: WaitForRunningLatencyDeployments
        Method: WaitForControlledPodsRunning
        Params:
          action: gather
  - name: Sleep for 2m before deleting pods
    measurements:
    - Identifier: sleep
      Method: Sleep
      Params:
        duration: 2m
  - name: Deleting Deployments
    phases:
      - namespaceRange:
          min: 1
          max: {{$namespaces}}
        replicasPerNamespace: 0
        tuningSet: DeploymentCreateQps
        objectBundle:
          - basename: deployment-churn
            objectTemplatePath: simple-deployment.yaml
  # - name: Wait to delete deployments
  #   measurements:
  #   - Identifier: sleep
  #     Method: Sleep
  #     Params:
  #       duration: 1s
  - name: Waiting for latency pods to be deleted
    measurements:
      - Identifier: WaitForRunningLatencyDeployments
        Method: WaitForControlledPodsRunning
        Params:
          action: gather
  {{end}}

  - name: Collecting measurements
    measurements:
      - Identifier: PodStartupLatency
        Method: PodStartupLatency
        Params:
          action: gather
      - Identifier: SchedulingThroughput
        Method: SchedulingThroughput
        Params:
          action: gather
      - Identifier: APIResponsivenessPrometheusSimple
        Method: APIResponsivenessPrometheus
        Params:
          action: gather
          enableViolations: true
          useSimpleLatencyQuery: true
          summaryName: APIResponsivenessPrometheus_simple