## Input params
{{$actionName := .actionName}}
{{$namespaces := .namespaces}}
{{$replicasPerNamespace := .replicasPerNamespace}}
{{$objectTemplatePath:= .objectTemplatePath}}

steps:
- name: "{{$actionName}} k8s services"
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$replicasPerNamespace}}
    tuningSet: Sequence
    objectBundle:
    - basename: test-service
      objectTemplatePath: {{$objectTemplatePath}}