apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: test-e8yiz2-1
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: my-service-1 # by convention, use the name of the Service
                     # as a prefix for the name of the EndpointSlice
  namespace: test-e8yiz2-1
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: my-service
addressType: IPv4
ports:
  - name: 'idk'
    appProtocol: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "10.4.5.6" # the IP addresses in this list can appear in any order
      - "10.244.2.199"
---
apiVersion: v1
kind: Endpoints
metadata:
  name: my-service
  namespace: test-e8yiz2-1
subsets:
  - addresses:
      - ip: 10.4.5.6
      - ip: 10.244.2.199
    ports:
      - port: 80
---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: my-destination-rule
#   namespace: test-e8yiz2-1
# spec:
#   host: my-service
#   trafficPolicy:
#     loadBalancer:
#       simple: RANDOM
#   subsets:
#   - name: v1
#     labels:
#       kubernetes.io/service-name: my-service